version: "3"
services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=True
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  django:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
      - .:/app
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
