# Generated by Django 3.2.8 on 2021-12-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='spouse_name',
            new_name='name',
        ),
    ]
